name: Nodejs Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

env: 
  ultros: ${{ github.event.head_commit.message }}
  # OMEGA: teste

jobs:
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.OMEGA }}
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        id: get_head_commit_message
        run: |
          OMEGA=$(echo $(git show -s --format=%s))
          echo "$OMEGA"
          echo "OMEGA=${OMEGA}" >> $GITHUB_OUTPUT

  print:
    name: Print
    needs: check_skip_flags
    runs-on: ubuntu-latest
    steps:
      - name: Print head git commit message
        run: |
          echo "${{ needs.check_skip_flags.outputs.head-commit-message }}"
          echo "${{ !contains(needs.check_skip_flags.outputs.head-commit-message, '[github-actions]') }}"
          echo "${{ !contains(needs.check_skip_flags.outputs.head-commit-message, 'wip(ci)') }}"
          echo "${{ contains(needs.check_skip_flags.outputs.head-commit-message, 'wip(ci)') }}"

  job_juvenal:
    name: Job Juvenal
    needs: print
    runs-on: ubuntu-latest
    if: ${{ contains(needs.check_skip_flags.outputs.head-commit-message, '[github-actions]') }}
    steps:
      - name: Print head git commit message
        run: |
          echo "Juvenal"

  job_omega:
    name: Job Omega
    needs: print
    runs-on: ubuntu-latest
    if: ${{ contains(needs.check_skip_flags.outputs.head-commit-message, 'wip(ci)') }}
    steps:
      - name: Print head git commit message
        run: |
          echo "Omega"


  build:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1

      - name: Instala as dependências
        run: npm install

      - name: Build da aplicação
        run: npm run build

  tests:
    needs: build
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1

      - name: Instala as dependências
        run: npm install

      - name: Executa os testes com coverage
        run: npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # log-github-event-goodies:
  #   name: "LOG Everything on GitHub Event"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Logging
  #       run: |
  #         echo $ultros
  #         echo ${{ env.ultros }}
  #         echo "${{ github.event.commit_message }}"
  #         echo "${{ github.event.head_commit.message }}"
  #         echo "${{ github.event.head_commit.message[0] }}"
  #         echo "${{ toJSON(github.event.head_commit.message) }}"
  #         echo "expression: ${{ contains(github.event.head_commit.message, '[github-actions]') }}"
  #         echo ${{ contains(github.event.head_commit.message, '[github-actions]') == false }}
  #         echo "${{ github.event.head_commit.id }}"
  #         echo "${{ github.commit_message }}"
  #         echo "${{ github.event.commits }}"
  #         echo "${{ github.event_name }}"
  #         echo "${{ github.ref }}"
  #         echo "${{ github.event.head_ref }}"
  #         echo "${{ github.head_ref }}"
  #         echo "${{ github.base_ref }}"

  update-version:
    # env:
    #   ultros: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # se a mensagem do commit não contém '[github-actions]' então executa o job
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[github-actions]') == false
    steps:
      - name: Checkout do projecto
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_ACTIONS_TOKEN }}

      - name: Configurar Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "pipeline@actions.com"

      # - name: Checkout PR
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_ACTIONS_TOKEN }}
      #   run: gh pr checkout ${{ github.event.pull_request.number }}

      # BRANCH_NAME=$(git log --oneline | awk -F'heliandro/' '{print $2}')
      # BRANCH_NAME=$(echo "${{ github.head_ref }}")

      - name: Determinar Tipo de Versão (Major, Minor, ou Patch)
        id: determinar_tipo_de_versao
        run: |
          echo $(git log --oneline | awk -F'heliandro/' '{print $2}')
          echo $(git log --merges -n 1)
          echo $(git log --merges -n 1 | awk -F'heliandro/' '{print $2}')
          echo "$ultros"
          
          BRANCH_NAME=$(echo "$ultros" | awk -F'heliandro/' '{print $2}')
          if [[ $BRANCH_NAME == "bugfix/"* ]]; then
            echo "tipo_de_versao=patch" >> $GITHUB_OUTPUT
          elif [[ $BRANCH_NAME == "feature/"* ]]; then
            echo "tipo_de_versao=minor" >> $GITHUB_OUTPUT
          elif [[ $BRANCH_NAME == "release/"* ]]; then
            echo "tipo_de_versao=major" >> $GITHUB_OUTPUT
          else
            echo "Branch não especificada ou incorreta. Result=$BRANCH_NAME"
          fi

      - name: Criar versão do projeto
        if: steps.determinar_tipo_de_versao.outputs.tipo_de_versao != ''
        id: criar_versao_do_projeto
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_ACTIONS_TOKEN }}
        run: |
          npm version ${{ steps.determinar_tipo_de_versao.outputs.tipo_de_versao }} -m "[github-actions]: atualizar versão do projeto"
          VERSION=$(node -p -e "require('./package.json').version")
          git push
          echo "versao=$VERSION" >> GITHUB_OUTPUT

      # - name: Criar Tag
      #   if: steps.criar_versao_do_projeto.outputs.versao != ''
      #   run: |
      #     VERSION=$(node -p -e "require('./package.json').version")
      #     git tag "v$VERSION"
      #     git push origin "v$VERSION"
